### ISSUE TITLE
[VM] You can expose array as read-only

### ISSUE THREAD

**Issue by absoftware** [emrdgrmnci/FirstLeague#2]
https://github.com/emrdgrmnci/FirstLeague/blob/ff7aafba7e9f79d9b873ed33672da0d53982178b/FirstLeague/Modules/Main/MainContracts.swift#L15

You can exchange
```
    var teamsCount: Int { get }

    func teams(index: Int) -> Result
```
with
```
var teams: [Result] { get }
```

**Comment by emrdgrmnci** [comment]
Issue solved
